version: '3'

services:
    mqtt-test-publisher:
        build:
            context: source
            dockerfile: Dockerfile
        image: ${MQTT_TEST_PUBLISHER_NAME}:${MQTT_TEST_PUBLISHER_IMAGE_TAG}
        hostname: &mqtt_test_publisher_name ${MQTT_TEST_PUBLISHER_NAME}
        container_name: *mqtt_test_publisher_name
        restart: always
        depends_on:
            - mqtt-broker
        env_file:
          - .env
