version: '3'

services:
    rabbitmq-test-publisher:
        build:
            context: source
        image: ${RABBITMQ_TEST_PUBLISHER_NAME}:${RABBITMQ_TEST_PUBLISHER_IMAGE_TAG}
        hostname: &rabbitmq_test_publisher_name ${RABBITMQ_TEST_PUBLISHER_NAME}
        container_name: *rabbitmq_test_publisher_name
        restart: always
        depends_on:
            - rabbitmq
        env_file:
            - .env