version: '3'

services:
    modbus-tcp-connector-KEBA-P30:
        container_name: ${CONNECTOR_NAME}
        build:
            context: source
        restart: always
        user: "${USER_ID}:${GROUP_ID}"
        environment:
            - CONNECTOR_NAME=${CONNECTOR_NAME}
            - DEBUG=${DEBUG}
            - POLL_SECONDS=${POLL_SECONDS}
            - SEND_RAW_MESSAGE_TO_DB=${SEND_RAW_MESSAGE_TO_DB}

            - DATAMAP_PATH=${DATAMAP_PATH}

            - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
            - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}

            - MODBUS_MASTER_IP=${MODBUS_MASTER_IP}
            - MODBUS_MASTER_PORT=${MODBUS_MASTER_PORT}
            - MODBUS_MAX_RETRIES=${MODBUS_MAX_RETRIES}
            - MODBUS_RETRY_WAIT_SECONDS=${MODBUS_RETRY_WAIT_SECONDS}
            - MODBUS_POLL_BREAK=${MODBUS_POLL_BREAK}
            - MODBUS_DISCONNECT_BETWEEN_POLLS=${MODBUS_DISCONNECT_BETWEEN_POLLS}
            - MODBUS_CONFIG_PATH=${MODBUS_CONFIG_PATH}