#!/bin/bash
# Change ownership to solve permission problems with writing to the files that are generated by the Blockinfinity library
chown -R bem:bem /bem
# Start the celery worker
celery -A tasks.celery_app worker --loglevel=info --pool=gevent --concurrency=20 -Q trading -n trading_worker --uid=999 --purge
